#!/usr/local/bin/bash

#========================================
# Load Dependencies
#========================================
source "${__shcompatibility_script_dir}/deps/shcore/shcore"

function _esed() {
  if _is_osx; then
    sed -E -i "" "$@"
  else
    sed -r -i "$@"
  fi
}

function _esed_in_place() {
  if _is_osx; then
    sed -E -i "" "$@"
  else
    sed -r -i "$@"
  fi
}