#!/usr/local/bin/bash

#========================================
# Load Dependencies
#========================================
__load "${BASH_SOURCE[0]}" "shcore"

function _esed() {
  if _is_osx; then
    sed -E -i "" "$@"
  else
    sed -r -i "$@"
  fi
}

function _esed_in_place() {
  if _is_osx; then
    sed -E -i "" "$@"
  else
    sed -r -i "$@"
  fi
}